// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znpedwoxwyqdjdhkakqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpucGVkd294d3lxZGpkaGtha3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDY1MzgsImV4cCI6MjA3Mzg4MjUzOH0.uei1c7AP4I8fs5FLKcaqvdeY9NkGWYeojiG28z95ckw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});