// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsuektuumhzdpoggqono.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzdWVrdHV1bWh6ZHBvZ2dxb25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTkxMzMsImV4cCI6MjA3MzUzNTEzM30.4_Ap60DFb_hRXinDTBTH7ILzcS3eAuifcBpUJKoat70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});