// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://dvufbepjnmlznqczxnkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2dWZiZXBqbm1sem5xY3p4bmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTA1MDEsImV4cCI6MjA3Mzc4NjUwMX0.4LsgEEsAGWIXewUN6H0QJs9lK4GQrCtIQRaIoRCQI_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});